### ISSUE TITLE
Blog Post Card images creates an error

### ISSUE THREAD

**Issue by niccokunzmann** [chrede88/qubt#188]
### What happened?

I added a new image and I get this error:

```
Error: error building site: render: failed to render pages: render of "section" failed: "/home/nicco/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/niccokunzmann/qubt@v1.5.2-0.20241129082442-5f7f9e6a6169/layouts/_default/section.html:22:40": execute of template failed: template: _default/section.html:22:40: executing "main" at <$cardimage.Filter>: error calling Filter: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

It seems that I have to create the image as 600x400 px and then the error goes away.

### Theme version

v1.5.0

### Hugo version

hugo v0.139.2-770f548b47b39e6f0fd4da1cc80552024e5829e1 linux/amd64 BuildDate=2024-11-23T15:33:51Z VendorInfo=gohugoio

### Which browser are you using?

Firefox

### Relevant Hugo log output

```shell
Error: error building site: render: failed to render pages: render of "section" failed: "/home/nicco/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/niccokunzmann/qubt@v1.5.2-0.20241129082442-5f7f9e6a6169/layouts/_default/section.html:22:40": execute of template failed: template: _default/section.html:22:40: executing "main" at <$cardimage.Filter>: error calling Filter: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

**Comment by niccokunzmann** [comment]
I found the problem: I installed the basic hugo version. Now, I have the extended version from
https://github.com/gohugoio/hugo/releases/tag/v0.139.2

**Comment by niccokunzmann** [comment]
I wonder if this needs documenting: Hugo Extended is required. Not the basic version. I do not know if this is documented... checking...

**Comment by chrede88** [comment]
Yes you'll need the extended version. I agree this should be added to the documentation. Good catch!
