### ISSUE TITLE
Preserve aspect ratio of post feature images

### ISSUE THREAD

**Issue by lpar** [chrede88/qubt#24]
### What happened?

The way posts' feature images get stretched out of proportion to 400x600 for list pages is a bit ugly. Turns out it's easy to fix. In `layouts/_default/section.html`, change:

```{{ $cardimage = $cardimage.Filter (images.Process "resize 400x600 webp" ) }}```

to

```{{ $cardimage = $cardimage.Filter (images.Process "fit 400x600 webp" ) }}```

### Theme version

v1.2.2

### Hugo version

v0.121.1

### Which browser are you using?

Safari

**Comment by chrede88** [comment]
Thanks for reporting this. You're completely right, I'll push a fix for this asap.

**Comment by chrede88** [comment]
Fixed in release [v1.2.3](https://github.com/chrede88/qubt/releases/tag/v1.2.3).
